/** ─── Barshi — Shared TypeScript Types ─── */

export type ProjectType =
  | 'game'
  | 'website'
  | 'tool'
  | 'story'
  | 'interface'
  | 'simulation'
  | 'world'

export type ProjectVisibility = 'private' | 'public' | 'removed'

export type AccountStatus = 'active' | 'warned' | 'restricted' | 'suspended' | 'banned'

export type NotificationType = 'like' | 'remix' | 'play_milestone' | 'publish_success' | 'moderation'

export type ReportReason = 'bullying' | 'inappropriate' | 'personal_info' | 'unsafe' | 'spam' | 'other'

export type ModerationAction = 'warning' | 'restrict_publishing' | 'suspend' | 'ban' | 'project_removed'

export type SafetySeverity = 'none' | 'low' | 'medium' | 'high'

/** Lightweight project metadata (NOT the runnable HTML) */
export interface ProjectMeta {
  type: ProjectType
  screens: string[]
  components: string[]
  theme: {
    primaryColor: string
    mood: string
  }
  usesKaboom: boolean
}

/** CSS cover card config (no screenshot needed in MVP) */
export interface CoverConfig {
  gradientFrom: string
  gradientTo: string
  accentColor: string
  icon: string
  patternType: 'dots' | 'grid' | 'none'
}

/** Build plan generated by Claude before full generation */
export interface BuildPlan {
  title: string
  type: ProjectType
  summary: string
  screens: string[]
  components: string[]
  rules: string[]
  theme: string
  usesKaboom: boolean
}

/** Intent form values from the user */
export interface CreationIntent {
  prompt: string
  type?: ProjectType
  forWho?: string
  mustInclude?: string
  style?: string
}

/** Safety scan result */
export interface SafetyScanResult {
  safe: boolean
  severity: SafetySeverity
  reasons: string[]
  action: 'allow' | 'flag' | 'block'
}

/** Fix issue from the Fix action */
export interface FixIssue {
  id: string
  title: string
  description: string
  severity: 'critical' | 'warning' | 'suggestion'
  fix: string // complete updated HTML with this fix applied
}

/** DB row types (matches Supabase schema) */
export interface Profile {
  id: string
  username: string
  avatar_url: string | null
  bio: string | null
  account_status: AccountStatus
  restriction_until: string | null
  created_at: string
}

export interface Project {
  id: string
  creator_id: string
  title: string
  description: string | null
  type: ProjectType
  meta_json: ProjectMeta
  bundle_path: string | null
  cover_config: CoverConfig
  visibility: ProjectVisibility
  remix_of: string | null
  play_count: number
  like_count: number
  remix_count: number
  published_at: string | null
  created_at: string
  updated_at: string
}

/** Project with creator profile joined */
export interface ProjectWithCreator extends Project {
  creator: Pick<Profile, 'id' | 'username' | 'avatar_url'>
}

export interface Notification {
  id: string
  user_id: string
  type: NotificationType
  data: Record<string, unknown>
  read: boolean
  created_at: string
}

export interface Report {
  id: string
  project_id: string
  reporter_id: string
  reason: ReportReason
  status: 'pending' | 'safe' | 'actioned'
  created_at: string
}
